version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: webdriverio
    versions:
    - 6.12.1
    - 7.0.1
    - 7.0.2
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
    - 7.0.9
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.2
    - 7.4.5
    - 7.4.6
    - 7.5.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: puppeteer
    versions:
    - 8.0.0
  - dependency-name: html-loader
    versions:
    - 1.3.2
    - 2.1.0
    - 2.1.1
  - dependency-name: cross-env
    versions:
    - 7.0.3
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
  - dependency-name: blob-polyfill
    versions:
    - 5.0.20210201
  - dependency-name: chai
    versions:
    - 4.3.0
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: bl
    versions:
    - 4.0.4
    - 4.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: xlsx
    versions:
    - 0.16.9
  - dependency-name: karma-firefox-launcher
    versions:
    - 2.1.0
  - dependency-name: mocha-loader
    versions:
    - 5.1.5
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
